name: Release creation

on: 
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Tipo de release'
        default: 'release'
        required: true

jobs:
  release-creation:
    runs-on: ubuntu-latest
    env:
      releaseVersion: 'default'

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      
      - if: github.event.inputs.releaseType == 'release'
        name: Get new release version
        run: releaseVersion=0.1.0
      
      - if: github.event.inputs.releaseType == 'fix'
        name: Get new release fix version
        run: releaseVersion=0.0.1
      
      - name: Pintar la versión
        run: echo "$releaseVersion"
      
      - name: Pintar la versión 2
        run: echo ${{env.releaseVersion}}
