name: Release creation

on: 
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Tipo de release'
        default: 'release'
        required: true

jobs:
  release-creation:
    runs-on: ubuntu-latest
    env:
      version: 'default'
      releaseVersion: 'default'

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - run: echo "version=$(awk '/appVersion = /{print$3}' platformio.ini)" >> $GITHUB_ENV

      - if: github.event.inputs.releaseType == 'release'
        name: Get new release version
        run: echo "releaseVersion=0.1.0" >> $GITHUB_ENV

      - if: github.event.inputs.releaseType == 'fix'
        name: Get new release fix version
        run: echo "releaseVersion=0.0.1" >> $GITHUB_ENV

      - name: Pintar la versión
        run: echo "$version y $releaseVersion"

      - name: Pintar la versión
        run: echo ${{env.releaseVersion}}
