name: Release creation

on: 
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Tipo de release'
        default: 'release'
        required: true

jobs:
  release-creation:
    runs-on: ubuntu-latest
    env:
      version: 'default'
      releaseVersion: 'default'

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - run: |
          versionActual=$(awk '/appVersion = /{print$3}' platformio.ini)
          versionActual=${versionActual/-SNAPSHOT/}
          echo "version=$versionActual" >> $GITHUB_ENV

      - if: github.event.inputs.releaseType == 'release'
        name: Get new release version
        run: |
          aVersion=(${version//./ })
          echo "releaseVersion=${aVersion[0]}.$((aVersion[1] + 1)).0" >> $GITHUB_ENV

      - if: github.event.inputs.releaseType == 'fix'
        name: Get new release fix version
        run: |
          aVersion=(${version//./ })
          echo "releaseVersion=${aVersion[0]}.${aVersion[1]}.$((aVersion[2] + 1))" >> $GITHUB_ENV

      - name: Pintar la versión
        run: echo "$version y $releaseVersion"

      - name: Replace release version to platformio.ini
        run: sed -i -e "s/appVersion = $version/appVersion = $releaseVersion/g" platformio.ini
